<html>
<head>
<!-- #BeginEditable "doctitle" --><title>ASUSTeK COMPUTER INC.</title><!-- #EndEditable --> 
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet" href="main.css">
<script language="JavaScript">
<!--
function MM_swapImgRestore() { //v3.0
	var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function MM_preloadImages() { //v3.0
	var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
		var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
		if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_swapImage() { //v3.0
	var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
	 if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</script>
<script language="JavaScript">
<!--
<!--
function MM_reloadPage(init) {	//reloads the window if Nav4 resized
	if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
		document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
	else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);
// -->

function MM_showHideLayers() { //v3.0
	var i,p,v,obj,args=MM_showHideLayers.arguments;
	for (i=0; i<(args.length-2); i+=3) if ((obj=MM_findObj(args[i]))!=null) { v=args[i+2];
		if (obj.style) { obj=obj.style; v=(v=='show')?'visible':(v='hide')?'hidden':v; }
		obj.visibility=v; }
}

function MM_jumpMenu(targ,selObj,restore){ //v3.0
	eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
	if (restore) selObj.selectedIndex=0;
}

function MM_openBrWindow(theURL,winName,features) { //v2.0
	window.open(theURL,winName,features);
}

function MM_findObj(n, d) { //v4.01
	var p,i,x;	if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
		d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
	if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
	for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
	if(!x && d.getElementById) x=d.getElementById(n); return x;
}
//-->
</script>
</head>
<body leftmargin="0" background="indeximages/bgdown.gif"	text="#000000" topmargin="0" onLoad="MM_preloadImages('indeximages/abouton.gif','indeximages/produon.gif','indeximages/supporon.gif','indeximages/regon.gif','indeximages/contacton.gif','indeximages/eserveon.gif','indeximages/topindex_r3_c3on.gif','indeximages/mb.gif','indeximages/topindex_r3_c5on.gif','indeximages/nb.gif','indeximages/topindex_r3_c7on.gif','indeximages/vga.gif','indeximages/topindex_r3_c9on.gif','indeximages/ia.gif','indeximages/topindex_r3_c11on.gif','indeximages/co.gif','indeximages/topindex_r3_c13on.gif','indeximages/sr.gif','indeximages/topindex_r3_c15on.gif','indeximages/os.gif')"	marginwidth="0" marginheight="0">
<table width=800 border="0" cellspacing="0" cellpadding="0">
	<tr> 
		<td rowspan="2" width="200" bgcolor="#FFFFFF"><a href="http://www.asus.com.tw/index.asp"><img src="indeximages/keyindex.jpg" width="200" height="87" border="0" alt="Welcome to ASUS"></a></td>
		<td	bgcolor="#FFFFFF"><img src="indeximages/spacer.gif" width="1" height="50" alt="banner" border="0"></td>
	</tr>
	<tr> 
		<td	bgcolor="#FFFFFF"> 
			<table border="0" cellspacing="0" cellpadding="0">
				<tr> 
					<td bgcolor="#FFFFFF" width="190"><img src="indeximages/logo.gif" width="160" height="34"></td>
					<td class="kimzbig2" width="287">Innovative Solutions for a Limitless Tomorrow</td>
					<td colspan="3" width="203"> 
						<table width="100%" border="0">
							<tr> 
								<td class="Kimzbig" width="48%">
									<div align="center"><font face="Arial">Global Site </font></div>
								</td>
								<form>
									<td width="52%"> 
										<select name="menu1" size=1 style="FONT-SIZE: 9pt" onChange="MM_jumpMenu('parent',this,0)" class="box">
											<option value="#" selected>Country Site</option>
											<option value="http://www.asus.com/index.asp">Global</option>
											<option value="http://www.asus.com.cn">China</option>
											<option value="http://france.asus.com">France</option>
											<option value="http://www.asuscom.de">Germany</option>
											<option value="http://www.asus.it">Italy</option>
											<option value="http://www.asus.co.jp">Japan</option>
											<option value="http://www.asus-korea.com">Korea</option>
											<option value="http://www.asuscom.ru">Russia</option>
											<option value="http://taiwan.asus.com.tw/index.htm">Taiwan</option>
											<option value="http://usa.asus.com/index.asp">USA</option>
										</select>
									</td>
								</form>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr> 
		<td background="indeximages/line_ext1.gif" colspan="2"> 
			<table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr> 
					<td> 
						<table border="0" cellpadding="0" cellspacing="0" width="502">
							<tr> 
								<td><img src="indeximages/spacer.gif" width="13" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="14" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="14" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="6" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="14" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="6" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="14" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="6" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="14" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="6" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="14" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="6" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="14" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="6" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="14" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="235" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="34" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="72" height="1" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="1" height="1" border="0"></td>
							</tr>
							<tr> 
								<td rowspan="5"><img name="topindex_r1_c1" src="indeximages/topindex_r1_c1.gif" width="13" height="38" border="0"></td>
								<td colspan="17"><img name="topindex_r1_c2" src="indeximages/topindex_r1_c2.gif" width="489" height="8" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="1" height="8" border="0"></td>
							</tr>
							<tr> 
								<td rowspan="6"><img name="topindex_r2_c2" src="indeximages/topindex_r2_c2.gif" width="14" height="43" border="0"></td>
								<td colspan="15"><img name="topindex_r2_c3" src="indeximages/topindex_r2_c3.gif" width="403" height="7" border="0"></td>
								<td rowspan="2"><img name="topindex_r2_c18" src="indeximages/topindex_r2_c18.gif" width="72" height="11" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="1" height="7" border="0"></td>
							</tr>
							<tr> 
								<td rowspan="2"><img name="topindex_r3_c3" src="indeximages/topindex_r3_c3.gif" width="14" height="14" border="0"></td>
								<td rowspan="2"><img name="topindex_r3_c4" src="indeximages/topindex_r3_c4.gif" width="6" height="14" border="0"></td>
								<td rowspan="2"><img name="topindex_r3_c5" src="indeximages/topindex_r3_c5.gif" width="14" height="14" border="0"></td>
								<td rowspan="2"><img name="topindex_r3_c6" src="indeximages/topindex_r3_c6.gif" width="6" height="14" border="0"></td>
								<td rowspan="2"><img name="topindex_r3_c7" src="indeximages/topindex_r3_c7.gif" width="14" height="14" border="0"></td>
								<td rowspan="2"><img name="topindex_r3_c8" src="indeximages/topindex_r3_c8.gif" width="6" height="14" border="0"></td>
								<td rowspan="2"><img name="topindex_r3_c9" src="indeximages/topindex_r3_c9.gif" width="14" height="14" border="0"></td>
								<td rowspan="2"><img name="topindex_r3_c10" src="indeximages/topindex_r3_c10.gif" width="6" height="14" border="0"></td>
								<td rowspan="2"><img name="topindex_r3_c11" src="indeximages/topindex_r3_c11.gif" width="14" height="14" border="0"></td>
								<td rowspan="2"><img name="topindex_r3_c12" src="indeximages/topindex_r3_c12.gif" width="6" height="14" border="0"></td>
								<td rowspan="2"><img name="topindex_r3_c13" src="indeximages/topindex_r3_c13.gif" width="14" height="14" border="0"></td>
								<td rowspan="2"><img name="topindex_r3_c14" src="indeximages/topindex_r3_c14.gif" width="6" height="14" border="0"></td>
								<td rowspan="2"><img name="topindex_r3_c15" src="indeximages/topindex_r3_c15.gif" width="14" height="14" border="0"></td>
								<td rowspan="2" colspan="2"><img name="topindex_r3_c16" src="indeximages/topindex_r3_c16.gif" width="269" height="14" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="1" height="4" border="0"></td>
							</tr>
							<tr> 
								<td><img name="topindex_r4_c18" src="indeximages/topindex_r4_c18.gif" width="72" height="10" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="1" height="10" border="0"></td>
							</tr>
							<tr> 
								<td rowspan="3" colspan="13"><img name="topindex_r5_c3" src="indeximages/topindex_r5_c3.gif" width="134" height="22" border="0"></td>
								<td rowspan="2"><img name="raps" src="indeximages/topindex_r5_c16.gif" width="235" height="14" border="0"></td>
								<td rowspan="3" colspan="2"><img name="topindex_r5_c17" src="indeximages/topindex_r5_c17.gif" width="106" height="22" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="1" height="9" border="0"></td>
							</tr>
							<tr> 
								<td rowspan="2"><img name="topindex_r6_c1" src="indeximages/topindex_r6_c1.gif" width="13" height="13" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="1" height="5" border="0"></td>
							</tr>
							<tr> 
								<td><img name="topindex_r7_c16" src="indeximages/topindex_r7_c16.gif" width="235" height="8" border="0"></td>
								<td><img src="indeximages/spacer.gif" width="1" height="8" border="0"></td>
							</tr>
						</table>
					</td>
					<td valign="top">&nbsp;</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<table width="760" border="0" cellspacing="0" cellpadding="0">
	<tr> 
		<td width="215" valign="top" bgcolor="#FFFFFF"> 
			<table border="0" cellspacing="0" cellpadding="0" width="208">
				<tr> 
					<td rowspan="7" width="175"><img src="indeximages/spacer.gif" width="1" height="1" alt="banner" border="0"></td>
					<td width="175"><img src="indeximages/spacer_j.gif" width="1" height="20"></td>
				</tr>
				<tr> 
					<td width="175"><a href="#" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image42','','indeximages/abouton.gif',1);MM_showHideLayers('member','','hide','servicesub','','hide','eservic','','hide','contact','','hide','service','','hide','products','','hide','about','','show')"><img name="Image42" border="0" src="indeximages/about.gif" width="175" height="15"></a></td>
				</tr>
				<tr> 
					<td width="175"><a href="#" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image43','','indeximages/produon.gif',1);MM_showHideLayers('member','','hide','servicesub','','hide','eservic','','hide','contact','','hide','service','','hide','products','','show','about','','hide')"><img name="Image43" border="0" src="indeximages/produ.gif" width="175" height="15"></a></td>
				</tr>
				<tr> 
					<td width="175"><a href="#" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image44','','indeximages/supporon.gif',1);MM_showHideLayers('member','','hide','servicesub','','hide','eservic','','hide','contact','','hide','service','','show','products','','hide','about','','hide')"><img name="Image44" border="0" src="indeximages/suppor.gif" width="175" height="15"></a></td>
				</tr>
				<tr> 
					<td width="175"><a href="#" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image45','','indeximages/regon.gif',1);MM_showHideLayers('member','','show','servicesub','','hide','eservic','','hide','contact','','hide','service','','hide','products','','hide','about','','hide')"><img name="Image45" border="0" src="indeximages/reg.gif" width="175" height="15"></a></td>
				</tr>
				<tr> 
					<td width="175"><a href="#" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image46','','indeximages/contacton.gif',1);MM_showHideLayers('member','','hide','servicesub','','hide','eservic','','hide','contact','','show','service','','hide','products','','hide','about','','hide')"><img name="Image46" border="0" src="indeximages/contact.gif" width="175" height="15"></a></td>
				</tr>
				<tr> 
					<td width="175"><a href="#" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image49','','indeximages/eserveon.gif',1);MM_showHideLayers('member','','hide','servicesub','','hide','eservic','','show','contact','','hide','service','','hide','products','','hide','about','','hide')"><img name="Image49" border="0" src="indeximages/eserve.gif" width="175" height="15"></a></td>
				</tr>
				<tr> 
					<td colspan="2"> 
						<div align="center"><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0" width="40" height="18">
								<param name=movie value="indeximages/moving.swf">
								<param name=quality value=high>
								<param name="wmode" value="transparent">
								<embed src="indeximages/moving.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="40" height="18" wmode="transparent">
								</embed> 
							</object></div>
					</td>
				</tr>
			</table>
		</td>
		<td width="545"> 
			<div align="right"><a href="mb/socketa/a7n266-e/overview.htm"><img src="indeximages/a7n266e-dolby.jpg" alt="ASUS A7N266-E Motherboard - the First Motherboard with Dolby Digital Logo Certification" 
			width="303" height="204" border="0"></a></div>
		</td>
	</tr>
</table>
<table width=800 border="0" cellspacing="0" cellpadding="0" height="30">
	<tr> 
		<td	background="indeximages/bgmi.gif" width="100%">&nbsp;</td>
	</tr>
</table>
<table cellspacing=0 cellpadding=0 width=774 border=0>
	<tbody> 
	<tr> 
		<td valign=top width=225> 
			<table cellspacing=0 cellpadding=0 width=225 border=0>
				<tbody> 
				<tr> 
					<td width=8 rowspan=10><font color=#ffffff>a</font></td>
					<td class=kimzbig width=180>Opinion &amp; Rating</td>
					<td width=37 rowspan=10>&nbsp;</td>
				</tr>
				<tr> 
					<td width=180 height=1><img height=15 src="indeximages/line.gif" 
						width=180></td>
				</tr>
				<tr> 
					<td width=180><img height=10 src="indeximages/bullettt.gif" 
						width=10><span class=Kimzsmall> Why do you prefer to make<br>
						on-line purchase?</span></td>
				</tr>
				<tr> 
					<td width=180> 
						<table cellspacing=0 cellpadding=0 width="97%" border=0>
							<tbody> 
							<tr> 
								<form name=vote1 action=program/vote.asp method=post>
									<td width="54%">
										<select style="FONT-SIZE: 9pt" size=1 
									name=select>
											<option value=1 selected>Price</option>
											<option 
										value=2>Time Saving</option>
											<option value=3>Web Only</option>
											<option value=4>Many Variety</option>
										</select>
										<input type=hidden value=001 name=qnumber>
										<input type=hidden 
									value=en name=language>
									</td>
									<td valign=top width="46%">
										<input type="submit" name="Submit" value="Vote" style="FONT-SIZE: 9pt">
									</td>
								</form>
							</tr>
							</tbody>
						</table>
					</td>
				</tr>
				<tr> 
					<td width=180><img height=10 src="indeximages/bullettt.gif" 
						width=10><span class=Kimzsmall> Which ASUS Socket 370 <br>
						motherboard do you like best?</span></td>
				</tr>
				<tr> 
					<form name=vote2 action=program/vote.asp method=post>
						<td width=180>
							<select style="FONT-SIZE: 9pt" size=1 name=select>
								<option value=1 selected>TUEG-VM</option>
								<option 
							value=2>TUA266</option>
								<option value=3>TUSL2</option>
								<option 
							value=4>CUV266-DLS</option>
							</select>
							<input type=hidden value=002 
						name=qnumber>
							<input type=hidden value=en name=language>
							<input type="submit" name="Submit2" value="Vote" style="FONT-SIZE: 9pt">
						</td>
					</form>
				</tr>
				<tr> 
					<td width=180><img height=10 src="indeximages/bullettt.gif" 
						width=10><span class=Kimzsmall> What would you look for when purchasing 
						a notebook?</span></td>
				</tr>
				<tr> 
					<form name=vote3 action=program/vote.asp method=post>
						<td width=180>
							<select style="FONT-SIZE: 9pt" size=1 name=select>
								<option value=1 selected>Design</option>
								<option 
							value=2>Speed</option>
								<option value=3>Lightweight</option>
								<option value=4>Features</option>
								<option value=5>Price</option>
								<option value=6>Low Thermal</option>
							</select>
							<input type=hidden 
						value=003 name=qnumber>
							<input type=hidden value=en name=language>
							<input type="submit" name="Submit3" value="Vote" style="FONT-SIZE: 9pt">
						</td>
					</form>
				</tr>
				<tr> 
					<td width=180 height=1><img height=15 src="indeximages/line.gif" 
						width=180></td>
				</tr>
				<tr> 
					 <form name=form6><td valign=top width=180> 
					 
							<img height=10 src="indeximages/bullettt.gif" 
						width=10><span class=kimzbig> Quick Links </span><!-- #BeginLibraryItem "/Library/quicklinks.lbi" --><select 
						style="FONT-SIZE: 9pt" onChange="MM_jumpMenu('parent',this,1)" 
						size=1 name=select><option value="#" selected>Choose One!!</option>
<option value="#">........................</option>
<option value="#">-About ASUS</option>
<option value="inside/corporatemission.htm">---Corporate Mission</option>
<option value="inside/employment.htm">---Employment</option>
<option value="http://www.asus.com">---Mirror Site</option>
<option value="inside/certificate.htm">---Certification</option>
<option value="#">-Product List</option>
<option value="inside/shortcut.htm#a">---A--C</option>
<option value="inside/shortcut.htm#d">---D--F</option>
<option value="inside/shortcut.htm#i">---G--I</option>
<option value="inside/shortcut.htm#i">---K--L</option>
<option value="inside/shortcut.htm#m">---M--R</option>
<option value="inside/shortcut.htm#v">---V--X</option>
<option value="inside/shortcut.htm#s">---S--U</option>
<option value="inside/shortcut.htm#v">---Y--Z</option>
<option value="#">-Award</option>
<option value="inside/awardmotherboard.htm">---Motherboard</option>
<option value="inside/awardvga.htm">---Multimedia</option>
<option value="inside/awardnotebook.htm">---Notebook</option>
<option value="inside/wheretobuy.htm">-Where to Buy</option>
<option value="inside/wheretobuy.htm">---Global Database</option>
<option value="inside/wheretobuy.htm">---Shops by Territory</option>
<option value="inside/getsupport.htm">-Service 
							and Support</option>
<option value="inside/CSC.htm">---Customer 
							Service Center</option>
<option value="inside/getsupport.htm">---How 
							to get support</option>
<option value="inside/GSM.htm">---GSM</option>
<option value="inside/warranty.htm">---Warranty Information</option>
<option value="register/register.htm">---Activate Your Warranty</option>
<option value="inside/technicalreference.htm">---Technical 
							Reference</option>
<option value="inside/downloadmap.htm">---Download</option>
<option value="#">-Manual</option>
<option value="download/manual/manual-index.htm">---Motherboard</option>
<option value="inside/multimanual.htm">---Multimedia</option>
<option value="download/manual/nbmanual.htm">---Notebook</option>
<option value="http://www.asusmall.com.tw/accounts/member/asp_eval/eval01.asp?l=_en">-Evaluate 
							ASUS</option>
<option value="mailto:webmaster@asus.com.tw">-Contact 
							ASUS</option>
<option value="mailto:tsd@asus.com.tw">---Technical 
							Support</option>
<option value="mailto:webmaster@asus.com.tw">---General Webmaster</option>
<option value="inside/mailinglist.htm">---Requesting Press</option>
<option value="mailto:webmaster@asus.com.tw">---Customer 
							Feedback</option>
<option value="#">-Registration</option>
<option value="http://www.asusmall.com.tw/accounts/member">---Product 
							Registration</option>
<option value="http://www.asusmall.com.tw/accounts/member/en_mem_reg.asp?lang=en">---Member's 
							Area</option>
<option value="http://reseller.asus.com.tw">---Reseller 
							Square</option>
<option value="http://channel.asus.com.tw">---Channel Site</option>
</select><!-- #EndLibraryItem -->
						
					</td></form>
				</tr>
				</tbody>
			</table>
		</td>
	 <td width=549> 
			<table cellspacing=0 cellpadding=0 width="100%" align=center border=0>
				<tbody> 
				<tr> 
					<td colspan=2><span class=kimzbig>News</span><br>
						<img height=15 
						src="indeximages/line.gif" width=227> </td>
				</tr>
				<tr> 
					<td valign="top" width="71" height="101"><img src="indeximages/newsicon.gif" width="70" height="70"> 
					</td>
					<td width="519" height="101" valign="top"> 
						<div align="center"> 
							<table width="100%" border="0" cellspacing="0" cellpadding="0">
								<tr>
									<td><a href="inside/downloadmap.htm" class="normal"><img src="indeximages/go_1.gif" width="134" height="50" border="0"></a></td>
									<td><a href="inside/technicalreference.htm" class="normal"><img src="indeximages/go_2.gif" width="134" height="50" border="0"></a> </td> 
									<td><a href="readme.htm" class="normal"><img src="indeximages/go_3.gif" width="134" height="50" border="0"></a></td>
								</tr>
							</table>
							<p align=left>
							
							
				<img height=8 src="indeximages/bullet.gif" 
						width=8><span class=Kimzsmall> <a class=normal 
						href="inside/milstone.htm">ASUS is ranked #4 in &quot;High Quality Service/Products&quot; in Taiwan in Asia's 
						Leading Companies survey, (Far Eastern Economic Review, December)</a>
						<img height=11 src="indeximages/new.gif" width=28></span><br>
				
						<img height=8 src="indeximages/bullet.gif" 
						width=8><span class=Kimzsmall> <a class=normal 
						href="inside/crw-3212a.htm">ASUS<sup>&reg;</sup> 
						 Announces 32X/ 12X/ 40X CD-RW Drive</a>
						</span><br>
						
						<img height=8 src="indeximages/bullet.gif" 
						width=8><span class=Kimzsmall> <a class=normal 
						href="inside/dolby.htm">ASUS<sup>&reg;</sup> 
						A7N266-E nForce<sup>TM</sup> Based Motherboard Receives Dolby Digital Logo Certification</a>
						</span><br>
						
						<img height=8 src="indeximages/bullet.gif" 
						width=8><span class=Kimzsmall> <a class=normal 
						href="inside/s1.htm">ASUS<sup>&reg;</sup> 
						Introduces the S1 Series Ultra-Portable Notebook PC</a>
						</span><br>
						
						<img height=8 src="indeximages/bullet.gif" 
						width=8><span class=Kimzsmall> <a class=normal 
						href="inside/p4b266.htm">ASUS<sup>&reg;</sup> 
						Releases P4B266 DDR Pentium 4 Motherboard with Intel 845D Chipset</a>
						</span><br>
						
						<img height=8 src="indeximages/bullet.gif" 
						width=8><span class=Kimzsmall> <a class=normal 
						href="inside/a7m266-d.htm">ASUS<sup>&reg;</sup> 
						Ships A7M266-D Dual Socket A Motherboard with AMD 760-MPX<sup>TM</sup> Chipset</a>
						</span>
					</p>
						</div>
					</td>
				</tr>
				<tr> 
					<td colspan=2>&nbsp;</td>
				</tr>
				<tr> 
					<td class=kimztitle colspan=2><span 
						class=kimzbig>Highlight</span><br>
						<img height=15 
						src="indeximages/line.gif" width=227> </td>
				</tr>
				<tr> 
					<td valign=top width=71><img height=70 
						src="indeximages/eventsicon.gif" width=70> </td>
					<td valign=top width=519>
					 <p align=left>
								<img height=8 
						src="indeximages/bullet.gif" width="8" border="0">
						<a class=normal href="inside/awardnotebook.htm#t9000">ASUS<sup>&reg;</sup> 
							 L8400C, T9 and M1 Series Notebook ALL Won PC World Best Buy Awards in Australia.</a> 
							 <img height=11 src="indeximages/new.gif" width=28><br>
							 
							 <a class=normal href="inside/awardnotebook.htm#a1000">ASUS<sup>&reg;</sup> 
							 A1 Series Notebook Wins PC World Best Buy Awards in Australia.</a> 
							 <img height=11 src="indeximages/new.gif" width=28><br>
							 
							 <img height=8 src="indeximages/bullet.gif" width=8 border="0"> <a class=normal href="inside/awardnotebook.htm#s1000">
								ASUS<sup>&reg;</sup> S1 Notebook Won &quot;Editor's Choice&quot;, (Advance PC, Hong Kong)</a>
								<img height=11 src="indeximages/new.gif" width=28><br>
		 
							 <img height=8 src="indeximages/bullet.gif" width=8 border="0"><a class=normal href="inside/awardmotherboard.htm#p4b266">
							 ASUS<sup>&reg;</sup> P4B266 is a &quot;Very good MBs with advanced features&quot;, (CHIP, Czech)</a>
								<img height=11 src="indeximages/new.gif" width=28><br>
								
								<img height=8	 src="indeximages/bullet.gif" width=8><a class=normal href="inside/awardvga.htm#v8200t5">ASUS<sup>&reg;</sup> 
								V8200T5 Series Received &quot;PC World Recommended Buy&quot;, (PC World, Malaysia)</a> 
								
								
				</td>
				</tr>
				<tr> 
					<td valign=top colspan=2>&nbsp;</td>
				</tr>
				<tr> 
					<td valign=top colspan=2> 
						<table height=150 cellspacing=0 cellpadding=0 width=544 border=0>
							<tbody> 
							<tr> 
								<td colspan=2 height=21><span class=kimzbig>Local Event</span><br>
									<img height=15 src="indeximages/line.gif" 
									width=227> </td>
							</tr>
							<tr> 
								<td valign=top width=70 rowspan=2><a 
									href="event/index.htm"><img height=70 
									src="indeximages/highlighticon.gif" width=70 border=0></a> </td>
								<td valign=top width=474 height=130><img height=8 
									src="indeximages/bullet.gif" width=8><span class=Kimzsmall> <a 
									class=normal 
									href="http://event.asus.com.tw/EXPO2001/index.htm">Welcome to 
									ASUS<sup>&reg;</sup> EXPO2001 Online Showroom</a> </span><br>
									<img height=8 
									src="indeximages/bullet.gif" width=8><span class=Kimzsmall> <a 
									class=normal 
									href="inside/whatsnew2110.htm#modz">ASUS 
									Seeking ALL CaseModz Fans to Win an ASUS Dream Machine</a></span>
							 <p>&nbsp;</p>
									<p>&nbsp;</p>
								</td>
							</tr>
							</tbody>
						</table>
					</td>
				</tr>
				</tbody>
			</table>
		</td>
	</tr>
	</tbody>
</table>
<table cellspacing=0 cellpadding=0 width="800" bgcolor=#ffffff border=0>
	<tbody> 
	<tr bgcolor=#000000> 
		<td colspan=2 height=2><img height=1 
			src="C:\Documents and Settings\Administrator\Desktop\eng_files\spacer(1).gif" 
			width=1></td>
	</tr>
	<tr> 
		<td colspan=2 height=2><img height=1 
			src="C:\Documents and Settings\Administrator\Desktop\eng_files\spacer(1).gif" 
			width=1></td>
	</tr>
	<tr> 
		<td bgcolor=#000000 colspan=2 height=1><img height=1 
			src="C:\Documents and Settings\Administrator\Desktop\eng_files\spacer(1).gif" 
			width=1></td>
	</tr>
	<tr> 
		<td colspan=2> 
			<div class=Kimzsmall align=right><a class=visited 
			onClick="MM_openBrWindow('inside/copyright.htm','opcd','scrollbars=yes,resizable=yes,width=600,height=600')" 
			href="index.asp#">Copyright &copy; By ASUSTeK Computer 
				Inc.All rights reserved.</a></div>
		</td>
	</tr>
	<tr> 
		<td width=1000 colspan=2>&nbsp;</td>
	</tr>
	<tr> 
		<td width=10><img height=1 
			src="indeximages%5Cspacer.gif" 
			width=1> </td>
		<form name=search action=program/search.asp method=post>
			<td align=left>
				<!--<img src="indeximages/spacer.gif" width="20" height="8">-->
				<a 
			class=kimzbig2 href="sitemap.htm">Site Map</a> 
				<input style="FONT-SIZE: 9pt" name=QryStr size="10">
				<input type=hidden value=exec 
			name=Action>
				<input type="submit" name="Submit4" value="Search" style="FONT-SIZE: 9pt">
			</td>
		</form>
	</tr>
	</tbody>
</table>
<div id="service" style="position:absolute; left:149px; top:148px; z-index:20; visibility: hidden"> 
	<table cellspacing=0 cellpadding=0 width=334 border=0>
		<tbody> 
		<tr> 
			<td valign=bottom width=24 rowspan=7><img height=110 
			src="indeximages/midline2.gif" width=52></td>
			<td width=251><a class=normal 
			href="inside/CSC.htm">Customer Service Center</a></td>
		</tr>
		<tr> 
			<td width=251><a class=normal 
			href="inside/getsupport.htm">How to Get Support</a> 
			</td>
		</tr>
		<tr> 
			<td width=251><a class=normal 
						href="inside/warranty.htm">Warranty Information 
				</a></td>
		</tr>
		<tr> 
			<td width=251><a class=normal 
						href="register/register.htm">Activate Your 
				Warranty</a></td>
		</tr>
		<tr> 
			<td width=251><a class=normal 
						href="inside/GSM.htm">International Notebook 
				Service(GSM)</a></td>
		</tr>
		<tr> 
			<td width=251><a class=normal 
						href="inside/TechnicalReference.htm">Technical 
				Reference</a></td>
		</tr>
		<tr> 
			<td width=251><a class=normal 
						href="inside/downloadmap.htm">Download</a></td>
		</tr>
		</tbody> 
	</table>
</div>
<div id="contact" style="position:absolute; left:126px; top:194px; z-index:18; visibility: hidden"> 
	<table cellspacing=0 cellpadding=0 width=233 border=0>
		<tbody> 
		<tr> 
			<td valign=bottom width=25 rowspan=6><img height=77 
									src="indeximages/contactarrow.gif" width=28></td>
			<td width=184><a class=normal 
									href="inside/allcontact.htm">Technical Support</a></td>
		</tr>
		<tr>
			<td width=184><a class=normal href="inside/wheretobuy.htm">Where to Buy</a></td>
		</tr>
		<tr> 
			<td width=184><a class=normal 
									href="http://www.asusmall.com.tw/accounts/member/asp_eval/eval01.asp?l=_en">Evaluate 
				ASUS</a></td>
		</tr>
		<tr> 
			<td width=184><a class=normal 
									href="inside/mailinglist.htm">Requesting for Press -Release</a></td>
		</tr>
		<tr> 
			<td width=184><a class=normal 
									href="inside/complaint.htm">Customer Feedback</a></td>
		</tr>
		<tr> 
			<td width=184><a class=normal 
									href="mailto:webmaster@asus.com.tw">General Webmaster</a></td>
		</tr>
		</tbody> 
	</table>
</div>
<div id="member" style="position:absolute; left:121px; top:183px; z-index:19; visibility: hidden"> 
	<table cellspacing=0 cellpadding=0 width="153" border=0>
		<tbody> 
		<tr> 
			<td width="129" rowspan=3><img height=55 src="indeximages/midline3.gif" 
			width=47></td>
			<td width="553"><a class=normal 
			href="http://www.asusmall.com.tw/accounts/member/">Member's Area</a></td>
		</tr>
		<tr> 
			<td width="553"><a class=normal 
			href="http://reseller.asus.com.tw/">Reseller Square </a></td>
		</tr>
		<tr> 
			<td width="553"><a class=normal href="http://channel.asus.com.tw/">Channel 
				Site</a></td>
		</tr>
		</tbody>
	</table>
</div>
<div id="eservic" style="position:absolute; left:127px; top:149px; z-index:17; visibility: hidden"> 
	<table height=95 cellspacing=0 cellpadding=0 width="318" border=0>
		<tbody> 
		<tr> 
			<td valign=bottom width="30" rowspan=7><img height=104 
			src="indeximages/eserarrow.gif" width=30></td>
			<td width="288"><a class=normal 
			href="http://www.asusemag.com.tw/">eMagazine</a></td>
		</tr>
		<tr> 
			<td width="288"><a class=normal 
			href="http://www.asusnetq.com.tw/english/">NetQ Technical Forum</a></td>
		</tr>
		<tr> 
			<td width="288"><a class=normal href="http://channel.asus.com.tw/">Channel 
				Site (for ASUS Authorized Distributors)</a></td>
		</tr>
		<tr> 
			<td width="288"><a class=normal 
			href="http://download.asus.com.tw/">Software Download</a></td>
		</tr>
		<tr> 
			<td width="288"><a class=normal 
			href="http://reseller.asus.com.tw/">Reseller Square (for ASUS Resellers)</a></td>
		</tr>
		<tr> 
			<td width="288"><a class=normal 
			href="http://www.asusmall.com.tw/accounts/member/en_mem_reg.asp?lang=en">Member's Area (for 
				Power-Users)</a></td>
		</tr>
		</tbody>
	</table>
</div>
<div id="products" style="position:absolute; left:120px; top:145px; z-index:21; visibility: hidden; width: 316px; height: 150px"> 
	<table height=96 cellspacing=0 cellpadding=0 width="100%" border=0>
		<tbody> 
		<tr> 
			<td valign=bottom rowspan=10><img height=150 
			src="indeximages/produarrow.gif" width=52></td>
			<td width="84%"><a class=normal 
			href="http://www.asus.com.tw/inside/whatsnew.htm">What's new</a></td>
		</tr>
		<tr> 
			<td width="84%">Award (<a class=normal 
			href="http://www.asus.com.tw/inside/awardmotherboard.htm">M/B, </a><a 
			class=normal 
			href="http://www.asus.com.tw/inside/awardnotebook.htm">NB</a>, <a 
			class=normal 
	href="http://www.asus.com.tw/inside/awardvga.htm">VGA</a>)</td>
		</tr>
		<tr> 
			<td width="84%"><a class=normal 
			href="http://www.asus.com.tw/mb/mbindex.htm">Motherboard</a></td>
		</tr>
		<tr> 
			<td width="84%"><a class=normal 
			href="http://www.asus.com.tw/notebook/nbindex.htm">Notebooks</a></td>
		</tr>
		<tr> 
			<td width="84%"><a class=normal 
			href="http://www.asus.com.tw/vga/vgaindex.htm">Graphic Cards</a></td>
		</tr>
		<tr> 
			<td width="84%"><a class=normal 
			href="http://www.asus.com.tw/optical/opindex.htm">Optical Storage</a></td>
		</tr>
		<tr> 
			<td width="84%"><a class=normal 
			href="http://www.asus.com.tw/server/srindex.htm">Server</a></td>
		</tr>
		<tr> 
			<td width="84%"><a class=normal 
			href="http://www.asus.com.tw/desktop/dtpindex.htm">Desktop</a></td>
		</tr>
		<tr> 
			<td width="84%"><a class=normal 
			href="http://www.asus.com.tw/communication/coindex.htm">Communication</a></td>
		</tr>
		<tr> 
			<td width="84%"><a class=normal 
			href="http://www.asus.com.tw/infoapp/iaindex.htm">Information Appliance 
				</a></td>
		</tr>
		</tbody>
	</table>
</div>
<div id="about" style="position:absolute; left:122px; top:160px; z-index:22; visibility: hidden"> 
	<table cellspacing=0 cellpadding=0 width="88%" border=0>
		<tbody> 
		<tr> 
			<td valign=bottom width="11%" rowspan=8><img height=119 
			src="indeximages/aboutarrow.gif" width=41></td>
			<td width="89%"><a class=normal 
			href="http://www.asus.com.tw/inside/corporatemission.htm">Corporate Mission</a></td>
		</tr>
		<tr> 
			<td width="89%"><a class=normal 
			href="http://www.asus.com.tw/inside/milstone.htm">Milestones</a></td>
		</tr>
		<tr> 
			<td width="89%"><a class=normal 
			href="http://www.asus.com.tw/inside/technicalexcellence.htm">Technical Excellence</a></td>
		</tr>
		<tr> 
			<td width="89%"><a class=normal 
			href="http://www.asus.com.tw/inside/FacilitiesBranch.htm">Facilities and 
				Branch</a></td>
		</tr>
		<tr> 
			<td width="89%"><a class=normal 
			href="http://www.asus.com.tw/inside/productline.htm">Product Lines</a></td>
		</tr>
		<tr> 
			<td width="89%"><a class=normal 
			href="http://www.asus.com.tw/inside/investorinfo.htm">Financial Information</a></td>
		</tr>
		<tr> 
			<td width="89%"><a class=normal 
			href="http://www.asus.com.tw/inside/presskit.htm">Press Kit</a></td>
		</tr>
		<tr> 
			<td width="89%"><a class=normal 
			href="http://www.asus.com.tw/inside/employment.htm">Employment</a></td>
		</tr>
		</tbody>
	</table>
</div>
</body>
</html>