vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Apr 2002 19:03:32 -0000
vti_extenderversion:SR|4.0.2.5322
vti_cacheddtm:TX|14 Apr 2002 19:03:32 -0000
vti_filesize:IR|2055
vti_cachedlinkinfo:VX|Q|indConfig.css S|indConfig.js H|index_flash.asp H|index_html.asp H|mailto:diguera@onda.com.br
vti_cachedsvcrellinks:VX|FQUS|odig_asp/indConfig.css FSUS|odig_asp/indConfig.js FHUS|odig_asp/index_flash.asp FHUS|odig_asp/index_html.asp NHUS|mailto:diguera@onda.com.br
vti_cachedtitle:SR|<       Odig©       >
vti_title:SR|<       Odig©       >
vti_cachedbodystyle:SR|<body class="pgConfig">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Description Desenvolvimento\\ de\\ sites HTTP-EQUIV=Keywords odig,\\ internet,\\ software,\\ hardware,\\ web,\\ site,\\ flash,\\ asp,\\ php,\\ java,\\ css,\\ delphi,\\ clipper,\\ programa,\\ audio,\\ design,\\ busca,\\ chat,\\ icq,\\ mp3,\\ download,\\ tecnologia
vti_backlinkinfo:VX|
